collections:
  news:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "news"
    values:
      layout: "news"
      highlight: false
      region: "Nacional"
      author: "Cristian Pascoal Gomes"