domain: abc360.com.br      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://abc360.com.br  # the base hostname and protocol for your site, e.g. http://example.com
livereload: true

collections:
  news:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "news"
    values:
      layout: news
      highlight: false
      region: Nacional
      author: Cristian Pascoal Gomes
      image-url: /assets/images/art/symbol.png
      image-source: Internet